### ISSUE TITLE
无法读取单词，有道，欧路也都一样

### ISSUE THREAD

**Issue by VinSeanLu** [lixvbnet/Dict2Anki#3]
[dict2Anki][INFO] Config has no changes.
[dict2Anki.dictionary.eudict][INFO] Cookie有效
[dict2Anki][INFO] Config has no changes.
[dict2Anki.dictionary.eudict][INFO] Cookie有效
[dict2Anki.dictionary.eudict][INFO] 单词本分组:[('全部生词本', '-1'), ('我的生词本', '0')]
[dict2Anki][INFO] 2 group(s): [('全部生词本', '-1'), ('我的生词本', '0')]
[dict2Anki][INFO] 选中单词本['全部生词本', '我的生词本']

**Comment by lixvbnet** [comment]
Not reproduced.
